### ISSUE TITLE
API call /flow_manager/v2/flows on POST is returning misleading response status

### ISSUE THREAD

**Issue by ArturoQuintana** [kytos/flow_manager#132]
@hdiogenes @italovalcy @ajoaoff @rmotitsuki 

- If the payload items field is empty, ﻿**it returns 200 when it should be 400**.
reflected on end-to-end test:
tests/test_e2e_20_flow_manager.py::TestE2EFlowManager::test_016_install_flows_should_fail

Code:
```
def test_016_install_flows_should_fail(self):

        payload = {}

        api_url = KYTOS_API + '/flow_manager/v2/flows'
        response = requests.post(api_url, data=json.dumps(payload),
                                 headers={'Content-type': 'application/json'})
        assert response.status_code == 400
```

The same happens with these cases:
```
payload = {
            "flows": [
            ]
        }
```
and
```
payload = {
            "flows": [
                {

                }
            ]
        }
```

- A not serializable JSON broke the application and ﻿**it should return a 400 error**.
case:
```
payload = {
            "flows": [
                {
                    "priority"
                }
            ]
        }
```
The issue mentioned above should be verified for any  not serializable JSON

**Comment by cmagnobarbosa** [comment]
Hi @ArturoQuintana, I think maybe have a misconception in the third case of the error you have reported. 
The error: `not serializable JSON`, occurs because of the test itself. The `json.dumps` cannot make this data serializable. In addition, I am working to solve the other cases in the PR https://github.com/kytos/flow_manager/pull/137

**Comment by ArturoQuintana** [comment]
Hi @cmagnobarbosa, thanks for getting back to me about this.
I am sorry about the misconception on this report from my side.
Kytos documentation specifies that 400 response code belong to all the cases that the JSON flow is not valid (https://napps.kytos.io/kytos/flow_manager)
A not serializable JSON match to that class, or not? 
If not, we should not take care of this, but how will the Napp behave if it receives a not serializable JSON? is the code caring about this possibility? How do we guarantee the Napp will always receive a serializable JSON?

**Comment by cmagnobarbosa** [comment]
Hi, @ArturoQuintana thanks for the reply.
A `JSON` that is not well-formed, including all data that is not in the expected format, will be handled. If NApp receives data such as that reported in the `not-serializable` case, the error will be handled to avoid this error from interrupting NApp.
