### ISSUE TITLE
Implement netmasks for OF1.3

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/flow_manager#34]
We currently support netmasks for IPv4 addresses in match fields for OpenFlow1.0 natively, because we can calculate the wildcard bits when packing. We need to implement the support for OpenFlow1.3 matches.

**Comment by ajoaoff** [comment]
In fact, the lack of support for that is not in this NApp, but in `kytos/of_core`. And not just for IPv4, but for all fields. The issue kytos/of_core#75 deals with it.

**Comment by hdiogenes** [comment]
Solved in kytos/of_core#75
