### ISSUE TITLE
Improve documentation by listing the Napp dependencies

### ISSUE THREAD

**Issue by italovalcy** [kytos/flow_manager#78]
Hi Kytos Team,

Every Kytos Napp have a README describing the a basic documentation and the installation process. For those who know the Kytos structure, they are familiar with kytos.json which describes the dependencies on other napps. It would be good if the README also have the information about the napp dependencies as well, so that who is not familiar with kytos could quickly see what is the dependencies.

Just to make it clear, this is only a suggestion for documentation improvement, since when you run "kytos napps install xxxx" the dependencies are already resolved.

**Comment by hdiogenes** [comment]
Done on #79.
